#!/bin/sh
ARCHFLAGS="-arch x86_64"
cd .. ; make ; cd tests
clang $ARCHFLAGS -gfull -c -o current-test.o -I.. "$1" || exit 1
llvm-g++ $ARCHFLAGS -gfull -o current-test current-test.o ../gc.o
./current-test || exit 1
# rm current-test current-test.o


